import React from 'react';
import { ChatData, AnalysisResult } from '../types';
import { Sparkles, MessageCircle, Clock, Heart, TrendingUp, Quote, Users } from 'lucide-react';

interface PDFTemplateProps {
    chatData: ChatData;
    analysis: AnalysisResult;
    chartImages?: Record<string, string>;
}

// A4 dimensions in pixels at 96 DPI
const A4_WIDTH = 794; // 210mm
const A4_HEIGHT = 1123; // 297mm

/**
 * PDF Ringkas Template (1-2 pages)
 * Contains: Cover, Summary, Key Stats, Highlights
 */
export const PDFRingkasTemplate: React.FC<PDFTemplateProps> = ({ chatData, analysis }) => {
    const participant1 = chatData.participants[0] || 'User 1';
    const participant2 = chatData.participants[1] || 'User 2';
    const startDate = chatData.dateRange?.start ? new Date(chatData.dateRange.start).toLocaleDateString('id-ID') : '-';
    const endDate = chatData.dateRange?.end ? new Date(chatData.dateRange.end).toLocaleDateString('id-ID') : '-';
    const durationDays = chatData.dateRange?.start && chatData.dateRange?.end
        ? Math.ceil((new Date(chatData.dateRange.end).getTime() - new Date(chatData.dateRange.start).getTime()) / (1000 * 60 * 60 * 24))
        : 0;

    return (
        <div className="pdf-container" style={{ width: `${A4_WIDTH}px`, backgroundColor: '#ffffff' }}>
            {/* Page 1: Cover */}
            <div className="pdf-page" style={{
                width: `${A4_WIDTH}px`,
                height: `${A4_HEIGHT}px`,
                padding: '60px',
                boxSizing: 'border-box',
                position: 'relative',
                pageBreakAfter: 'always',
                background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)'
            }}>
                {/* Cover Content */}
                <div style={{ textAlign: 'center', color: '#ffffff', paddingTop: '120px' }}>
                    <div style={{ fontSize: '18px', fontWeight: '600', letterSpacing: '3px', marginBottom: '20px', opacity: 0.9 }}>
                        CHAT WRAPPED 2026
                    </div>
                    <h1 style={{ fontSize: '48px', fontWeight: '900', margin: '0 0 30px 0', lineHeight: '1.2' }}>
                        {participant1} × {participant2}
                    </h1>
                    <div style={{ fontSize: '20px', fontWeight: '600', marginBottom: '40px', opacity: 0.95 }}>
                        {analysis.relationshipType || 'Sahabat'}
                    </div>

                    {/* Key Stats Grid */}
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px', maxWidth: '500px', margin: '0 auto 60px' }}>
                        <div style={{ background: 'rgba(255,255,255,0.15)', padding: '20px', borderRadius: '12px', backdropFilter: 'blur(10px)' }}>
                            <div style={{ fontSize: '36px', fontWeight: '900', marginBottom: '5px' }}>{chatData.totalMessages?.toLocaleString()}</div>
                            <div style={{ fontSize: '14px', opacity: 0.9 }}>Total Pesan</div>
                        </div>
                        <div style={{ background: 'rgba(255,255,255,0.15)', padding: '20px', borderRadius: '12px', backdropFilter: 'blur(10px)' }}>
                            <div style={{ fontSize: '36px', fontWeight: '900', marginBottom: '5px' }}>{durationDays}</div>
                            <div style={{ fontSize: '14px', opacity: 0.9 }}>Hari</div>
                        </div>
                    </div>

                    <div style={{ fontSize: '16px', lineHeight: '1.8', maxWidth: '600px', margin: '0 auto', opacity: 0.95 }}>
                        {analysis.summary || 'Recap percakapan kalian yang penuh cerita.'}
                    </div>
                </div>

                {/* Footer */}
                <div style={{ position: 'absolute', bottom: '40px', left: '60px', right: '60px', textAlign: 'center', color: '#ffffff', opacity: 0.8 }}>
                    <div style={{ fontSize: '12px' }}>
                        {startDate} — {endDate}
                    </div>
                    <div style={{ fontSize: '10px', marginTop: '10px' }}>
                        Generated by RecapChat.app • {new Date().toLocaleDateString('id-ID')}
                    </div>
                </div>
            </div>

            {/* Page 2: Statistics */}
            <div className="pdf-page" style={{
                width: `${A4_WIDTH}px`,
                height: `${A4_HEIGHT}px`,
                padding: '60px',
                boxSizing: 'border-box',
                position: 'relative',
                pageBreakAfter: 'always',
                backgroundColor: '#ffffff'
            }}>
                <h2 style={{ fontSize: '32px', fontWeight: '900', color: '#1a1a1a', marginBottom: '40px', borderBottom: '4px solid #667eea', paddingBottom: '15px' }}>
                    Statistik Utama
                </h2>

                {/* Who Talks More */}
                <div style={{ marginBottom: '40px' }}>
                    <h3 style={{ fontSize: '20px', fontWeight: '700', color: '#333', marginBottom: '20px', display: 'flex', alignItems: 'center', gap: '10px' }}>
                        Siapa yang Lebih Banyak Ngobrol?
                    </h3>
                    <div style={{ display: 'flex', gap: '20px' }}>
                        {chatData.participants.map((participant, idx) => {
                            const stats = chatData.participantStats[participant];
                            const percentage = ((stats?.messageCount || 0) / chatData.totalMessages * 100).toFixed(1);
                            return (
                                <div key={idx} style={{ flex: 1, background: '#f8f9fa', padding: '20px', borderRadius: '12px', border: '2px solid #e9ecef' }}>
                                    <div style={{ fontSize: '18px', fontWeight: '700', color: '#333', marginBottom: '10px' }}>{participant}</div>
                                    <div style={{ fontSize: '32px', fontWeight: '900', color: '#667eea', marginBottom: '5px' }}>{stats?.messageCount?.toLocaleString()}</div>
                                    <div style={{ fontSize: '14px', color: '#666' }}>{percentage}% dari total</div>
                                </div>
                            );
                        })}
                    </div>
                </div>

                {/* Top Topics */}
                {analysis.topTopics && analysis.topTopics.length > 0 && (
                    <div style={{ marginBottom: '40px' }}>
                        <h3 style={{ fontSize: '20px', fontWeight: '700', color: '#333', marginBottom: '20px' }}>
                            Topik Paling Sering
                        </h3>
                        <div style={{ display: 'flex', flexWrap: 'wrap', gap: '12px' }}>
                            {analysis.topTopics.slice(0, 5).map((topic, idx) => (
                                <div key={idx} style={{
                                    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
                                    color: '#fff',
                                    padding: '12px 20px',
                                    borderRadius: '24px',
                                    fontSize: '14px',
                                    fontWeight: '600'
                                }}>
                                    {topic.emoji} {topic.topic} <span style={{ opacity: 0.8 }}>({topic.count}x)</span>
                                </div>
                            ))}
                        </div>
                    </div>
                )}

                {/* Top Emoji */}
                {(analysis.topEmoji1 || analysis.topEmoji2) && (
                    <div style={{ marginBottom: '40px' }}>
                        <h3 style={{ fontSize: '20px', fontWeight: '700', color: '#333', marginBottom: '20px' }}>
                            Emoji Favorit
                        </h3>
                        <div style={{ display: 'flex', gap: '15px' }}>
                            {analysis.topEmoji1 && (
                                <div style={{ textAlign: 'center', background: '#f8f9fa', padding: '15px', borderRadius: '12px', flex: 1 }}>
                                    <div style={{ fontSize: '40px', marginBottom: '8px' }}>{analysis.topEmoji1}</div>
                                    <div style={{ fontSize: '14px', fontWeight: '600', color: '#666' }}>{participant1}</div>
                                    <div style={{ fontSize: '12px', color: '#999' }}>{analysis.emojiCount1}x</div>
                                </div>
                            )}
                            {analysis.topEmoji2 && (
                                <div style={{ textAlign: 'center', background: '#f8f9fa', padding: '15px', borderRadius: '12px', flex: 1 }}>
                                    <div style={{ fontSize: '40px', marginBottom: '8px' }}>{analysis.topEmoji2}</div>
                                    <div style={{ fontSize: '14px', fontWeight: '600', color: '#666' }}>{participant2}</div>
                                    <div style={{ fontSize: '12px', color: '#999' }}>{analysis.emojiCount2}x</div>
                                </div>
                            )}
                        </div>
                    </div>
                )}

                {/* Best Quote */}
                {analysis.bestQuote && (
                    <div style={{ marginBottom: '30px' }}>
                        <h3 style={{ fontSize: '20px', fontWeight: '700', color: '#333', marginBottom: '20px' }}>
                            Quote Terbaik
                        </h3>
                        <div style={{ background: 'linear-gradient(135deg, #f8f9fa 0%, #e9ecef 100%)', padding: '30px', borderRadius: '16px', borderLeft: '6px solid #667eea' }}>
                            <p style={{ fontSize: '18px', fontStyle: 'italic', color: '#333', margin: '0 0 15px 0', lineHeight: '1.6' }}>
                                "{analysis.bestQuote}"
                            </p>
                            <div style={{ fontSize: '14px', color: '#666', fontWeight: '600' }}>
                                — {analysis.quoteAuthor || participant1}
                            </div>
                        </div>
                    </div>
                )}

                {/* Footer */}
                <div style={{ position: 'absolute', bottom: '40px', left: '60px', right: '60px', textAlign: 'center', color: '#999', fontSize: '10px', borderTop: '1px solid #e9ecef', paddingTop: '15px' }}>
                    <div>Generated by RecapChat.app • {new Date().toLocaleDateString('id-ID')}</div>
                    <div style={{ marginTop: '5px' }}>Halaman 2/2</div>
                </div>
            </div>
        </div>
    );
};

/**
 * PDF Full Report Template (Multi-page)
 * Contains: Everything from Ringkas + More detailed analysis
 */
export const PDFFullReportTemplate: React.FC<PDFTemplateProps> = ({ chatData, analysis }) => {
    const participant1 = chatData.participants[0] || 'User 1';
    const participant2 = chatData.participants[1] || 'User 2';
    const startDate = chatData.dateRange?.start ? new Date(chatData.dateRange.start).toLocaleDateString('id-ID') : '-';
    const endDate = chatData.dateRange?.end ? new Date(chatData.dateRange.end).toLocaleDateString('id-ID') : '-';
    const durationDays = chatData.dateRange?.start && chatData.dateRange?.end
        ? Math.ceil((new Date(chatData.dateRange.end).getTime() - new Date(chatData.dateRange.start).getTime()) / (1000 * 60 * 60 * 24))
        : 0;

    // Calculate total pages
    let totalPages = 4; // Base pages
    if (analysis.topTopics && analysis.topTopics.length > 0) totalPages++;
    if (analysis.prediction2026) totalPages++;

    return (
        <div className="pdf-container" style={{ width: `${A4_WIDTH}px`, backgroundColor: '#ffffff' }}>
            {/* Page 1: Cover (Same as Ringkas) */}
            <div className="pdf-page" style={{
                width: `${A4_WIDTH}px`,
                height: `${A4_HEIGHT}px`,
                padding: '60px',
                boxSizing: 'border-box',
                position: 'relative',
                pageBreakAfter: 'always',
                background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)'
            }}>
                <div style={{ textAlign: 'center', color: '#ffffff', paddingTop: '120px' }}>
                    <div style={{ fontSize: '18px', fontWeight: '600', letterSpacing: '3px', marginBottom: '20px', opacity: 0.9 }}>
                        CHAT WRAPPED 2026 • FULL REPORT
                    </div>
                    <h1 style={{ fontSize: '48px', fontWeight: '900', margin: '0 0 30px 0', lineHeight: '1.2' }}>
                        {participant1} × {participant2}
                    </h1>
                    <div style={{ fontSize: '20px', fontWeight: '600', marginBottom: '40px', opacity: 0.95 }}>
                        {analysis.relationshipType || 'Sahabat'}
                    </div>

                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px', maxWidth: '500px', margin: '0 auto 60px' }}>
                        <div style={{ background: 'rgba(255,255,255,0.15)', padding: '20px', borderRadius: '12px', backdropFilter: 'blur(10px)' }}>
                            <div style={{ fontSize: '36px', fontWeight: '900', marginBottom: '5px' }}>{chatData.totalMessages?.toLocaleString()}</div>
                            <div style={{ fontSize: '14px', opacity: 0.9 }}>Total Pesan</div>
                        </div>
                        <div style={{ background: 'rgba(255,255,255,0.15)', padding: '20px', borderRadius: '12px', backdropFilter: 'blur(10px)' }}>
                            <div style={{ fontSize: '36px', fontWeight: '900', marginBottom: '5px' }}>{durationDays}</div>
                            <div style={{ fontSize: '14px', opacity: 0.9 }}>Hari</div>
                        </div>
                    </div>

                    <div style={{ fontSize: '16px', lineHeight: '1.8', maxWidth: '600px', margin: '0 auto', opacity: 0.95 }}>
                        {analysis.summary || 'Recap lengkap percakapan kalian yang penuh cerita.'}
                    </div>
                </div>

                <div style={{ position: 'absolute', bottom: '40px', left: '60px', right: '60px', textAlign: 'center', color: '#ffffff', opacity: 0.8 }}>
                    <div style={{ fontSize: '12px' }}>
                        {startDate} — {endDate}
                    </div>
                    <div style={{ fontSize: '10px', marginTop: '10px' }}>
                        Generated by RecapChat.app • {new Date().toLocaleDateString('id-ID')}
                    </div>
                </div>
            </div>

            {/* Page 2: Overview & Stats */}
            <div className="pdf-page" style={{
                width: `${A4_WIDTH}px`,
                height: `${A4_HEIGHT}px`,
                padding: '60px',
                boxSizing: 'border-box',
                position: 'relative',
                pageBreakAfter: 'always',
                backgroundColor: '#ffffff'
            }}>
                <h2 style={{ fontSize: '32px', fontWeight: '900', color: '#1a1a1a', marginBottom: '30px', borderBottom: '4px solid #667eea', paddingBottom: '15px' }}>
                    Ringkasan Percakapan
                </h2>

                {/* Summary */}
                <div style={{ marginBottom: '30px', background: '#f8f9fa', padding: '25px', borderRadius: '12px', borderLeft: '6px solid #667eea' }}>
                    <p style={{ fontSize: '14px', lineHeight: '1.8', color: '#333', margin: 0 }}>
                        {analysis.summary}
                    </p>
                </div>

                {/* Key Metrics Grid */}
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '20px', marginBottom: '30px' }}>
                    <div style={{ background: '#f8f9fa', padding: '20px', borderRadius: '12px', textAlign: 'center', border: '2px solid #e9ecef' }}>
                        <div style={{ fontSize: '28px', fontWeight: '900', color: '#333', marginBottom: '5px' }}>{chatData.totalMessages?.toLocaleString()}</div>
                        <div style={{ fontSize: '12px', color: '#666' }}>Total Pesan</div>
                    </div>
                    <div style={{ background: '#f8f9fa', padding: '20px', borderRadius: '12px', textAlign: 'center', border: '2px solid #e9ecef' }}>
                        <div style={{ fontSize: '28px', fontWeight: '900', color: '#333', marginBottom: '5px' }}>{durationDays}</div>
                        <div style={{ fontSize: '12px', color: '#666' }}>Hari Aktif</div>
                    </div>
                    <div style={{ background: '#f8f9fa', padding: '20px', borderRadius: '12px', textAlign: 'center', border: '2px solid #e9ecef' }}>
                        <div style={{ fontSize: '28px', fontWeight: '900', color: '#333', marginBottom: '5px' }}>{Math.round((chatData.totalMessages || 0) / (durationDays || 1))}</div>
                        <div style={{ fontSize: '12px', color: '#666' }}>Pesan/Hari</div>
                    </div>
                </div>

                {/* Who Talks More */}
                <div style={{ marginBottom: '30px' }}>
                    <h3 style={{ fontSize: '20px', fontWeight: '700', color: '#333', marginBottom: '20px' }}>
                        Kontribusi Percakapan
                    </h3>
                    <div style={{ display: 'flex', gap: '20px' }}>
                        {chatData.participants.map((participant, idx) => {
                            const stats = chatData.participantStats[participant];
                            const percentage = ((stats?.messageCount || 0) / chatData.totalMessages * 100).toFixed(1);
                            return (
                                <div key={idx} style={{ flex: 1, background: '#f8f9fa', padding: '20px', borderRadius: '12px', border: '2px solid #e9ecef' }}>
                                    <div style={{ fontSize: '16px', fontWeight: '700', color: '#333', marginBottom: '10px' }}>{participant}</div>
                                    <div style={{ fontSize: '32px', fontWeight: '900', color: '#667eea', marginBottom: '5px' }}>{stats?.messageCount?.toLocaleString()}</div>
                                    <div style={{ fontSize: '14px', color: '#666', marginBottom: '10px' }}>{percentage}% dari total</div>
                                    <div style={{ fontSize: '12px', color: '#999' }}>
                                        Rata-rata {stats?.averageLength || 0} kata/pesan
                                    </div>
                                </div>
                            );
                        })}
                    </div>
                </div>

                {/* Mood & Confidence */}
                {(analysis.emotionalTone || analysis.aiConfidence) && (
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px' }}>
                        {analysis.emotionalTone && (
                            <div style={{ background: 'linear-gradient(135deg, #ffeaa7 0%, #fdcb6e 100%)', padding: '20px', borderRadius: '12px' }}>
                                <div style={{ fontSize: '14px', fontWeight: '600', color: '#333', marginBottom: '8px' }}>Mood Dominan</div>
                                <div style={{ fontSize: '24px', fontWeight: '900', color: '#2d3436' }}>{analysis.emotionalTone}</div>
                            </div>
                        )}
                        {analysis.aiConfidence && (
                            <div style={{ background: 'linear-gradient(135deg, #a29bfe 0%, #6c5ce7 100%)', padding: '20px', borderRadius: '12px' }}>
                                <div style={{ fontSize: '14px', fontWeight: '600', color: '#fff', marginBottom: '8px' }}>AI Confidence</div>
                                <div style={{ fontSize: '24px', fontWeight: '900', color: '#fff' }}>{analysis.aiConfidence.toUpperCase()}</div>
                            </div>
                        )}
                    </div>
                )}

                {/* Footer */}
                <div style={{ position: 'absolute', bottom: '40px', left: '60px', right: '60px', textAlign: 'center', color: '#999', fontSize: '10px', borderTop: '1px solid #e9ecef', paddingTop: '15px' }}>
                    <div>Generated by RecapChat.app • {new Date().toLocaleDateString('id-ID')}</div>
                    <div style={{ marginTop: '5px' }}>Halaman 2/{totalPages}</div>
                </div>
            </div>

            {/* Page 3: Topics & Quotes */}
            {(analysis.topTopics || analysis.bestQuote) && (
                <div className="pdf-page" style={{
                    width: `${A4_WIDTH}px`,
                    height: `${A4_HEIGHT}px`,
                    padding: '60px',
                    boxSizing: 'border-box',
                    position: 'relative',
                    pageBreakAfter: 'always',
                    backgroundColor: '#ffffff'
                }}>
                    <h2 style={{ fontSize: '32px', fontWeight: '900', color: '#1a1a1a', marginBottom: '30px', borderBottom: '4px solid #667eea', paddingBottom: '15px' }}>
                        Topik & Quote Terbaik
                    </h2>

                    {/* Top Topics */}
                    {analysis.topTopics && analysis.topTopics.length > 0 && (
                        <div style={{ marginBottom: '40px' }}>
                            <h3 style={{ fontSize: '20px', fontWeight: '700', color: '#333', marginBottom: '20px' }}>
                                Topik yang Paling Sering Dibahas
                            </h3>
                            <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                                {analysis.topTopics.slice(0, 5).map((topic, idx) => (
                                    <div key={idx} style={{
                                        background: idx === 0 ? 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)' : '#f8f9fa',
                                        color: idx === 0 ? '#fff' : '#333',
                                        padding: '20px 24px',
                                        borderRadius: '12px',
                                        display: 'flex',
                                        alignItems: 'center',
                                        gap: '20px',
                                        border: idx === 0 ? 'none' : '2px solid #e9ecef'
                                    }}>
                                        <div style={{ fontSize: '24px', fontWeight: '900', minWidth: '40px' }}>#{idx + 1}</div>
                                        <div style={{ fontSize: '32px' }}>{topic.emoji}</div>
                                        <div style={{ flex: 1 }}>
                                            <div style={{ fontSize: '18px', fontWeight: '700', marginBottom: '5px' }}>{topic.topic}</div>
                                            <div style={{ fontSize: '14px', opacity: idx === 0 ? 0.9 : 0.7 }}>{topic.count} pesan</div>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}

                    {/* Best Quote */}
                    {analysis.bestQuote && (
                        <div style={{ marginBottom: '30px' }}>
                            <h3 style={{ fontSize: '20px', fontWeight: '700', color: '#333', marginBottom: '20px' }}>
                                Quote Terbaik Tahun Ini
                            </h3>
                            <div style={{ background: 'linear-gradient(135deg, #f8f9fa 0%, #e9ecef 100%)', padding: '40px', borderRadius: '16px', borderLeft: '8px solid #667eea', position: 'relative' }}>
                                <div style={{ fontSize: '64px', color: '#667eea', opacity: 0.2, position: 'absolute', top: '20px', left: '30px' }}>"</div>
                                <p style={{ fontSize: '20px', fontStyle: 'italic', color: '#333', margin: '0 0 20px 0', lineHeight: '1.7', paddingLeft: '40px' }}>
                                    {analysis.bestQuote}
                                </p>
                                <div style={{ fontSize: '16px', color: '#666', fontWeight: '700', paddingLeft: '40px' }}>
                                    — {analysis.quoteAuthor || participant1}
                                </div>
                                {analysis.quoteDate && (
                                    <div style={{ fontSize: '12px', color: '#999', marginTop: '10px', paddingLeft: '40px' }}>
                                        {analysis.quoteDate}
                                    </div>
                                )}
                            </div>
                        </div>
                    )}

                    {/* Runner Up Quotes */}
                    {analysis.runnerUpQuotes && analysis.runnerUpQuotes.length > 0 && (
                        <div>
                            <h3 style={{ fontSize: '16px', fontWeight: '700', color: '#666', marginBottom: '15px', textTransform: 'uppercase', letterSpacing: '1px' }}>
                                Runner Ups
                            </h3>
                            <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                                {analysis.runnerUpQuotes.slice(0, 2).map((quote, idx) => (
                                    <div key={idx} style={{ background: '#f8f9fa', padding: '20px', borderRadius: '12px', border: '2px solid #e9ecef' }}>
                                        <p style={{ fontSize: '14px', fontStyle: 'italic', color: '#333', margin: '0 0 10px 0', lineHeight: '1.6' }}>
                                            "{quote.text}"
                                        </p>
                                        <div style={{ fontSize: '12px', color: '#666', fontWeight: '600' }}>
                                            — {quote.author}
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}

                    {/* Footer */}
                    <div style={{ position: 'absolute', bottom: '40px', left: '60px', right: '60px', textAlign: 'center', color: '#999', fontSize: '10px', borderTop: '1px solid #e9ecef', paddingTop: '15px' }}>
                        <div>Generated by RecapChat.app • {new Date().toLocaleDateString('id-ID')}</div>
                        <div style={{ marginTop: '5px' }}>Halaman 3/{totalPages}</div>
                    </div>
                </div>
            )}

            {/* Page 4: AI Insights & Predictions */}
            <div className="pdf-page" style={{
                width: `${A4_WIDTH}px`,
                height: `${A4_HEIGHT}px`,
                padding: '60px',
                boxSizing: 'border-box',
                position: 'relative',
                backgroundColor: '#ffffff'
            }}>
                <h2 style={{ fontSize: '32px', fontWeight: '900', color: '#1a1a1a', marginBottom: '30px', borderBottom: '4px solid #667eea', paddingBottom: '15px', display: 'flex', alignItems: 'center', gap: '15px' }}>
                    AI Insights & Prediksi
                </h2>

                {/* Relationship Analysis */}
                {analysis.relationshipType && (
                    <div style={{ marginBottom: '30px', background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', padding: '30px', borderRadius: '16px', color: '#fff' }}>
                        <div style={{ fontSize: '14px', fontWeight: '600', marginBottom: '10px', opacity: 0.9 }}>Tipe Hubungan</div>
                        <div style={{ fontSize: '28px', fontWeight: '900', marginBottom: '15px' }}>{analysis.relationshipType}</div>
                        {analysis.summary && (
                            <div style={{ fontSize: '14px', lineHeight: '1.7', opacity: 0.95 }}>
                                {analysis.summary}
                            </div>
                        )}
                    </div>
                )}

                {/* Prediction 2026 */}
                {analysis.prediction2026 && (
                    <div style={{ marginBottom: '30px' }}>
                        <h3 style={{ fontSize: '20px', fontWeight: '700', color: '#333', marginBottom: '15px' }}>
                            🔮 Prediksi 2026
                        </h3>
                        <div style={{ background: 'linear-gradient(135deg, #ffeaa7 0%, #fdcb6e 100%)', padding: '30px', borderRadius: '16px', border: '3px solid #fdcb6e' }}>
                            <p style={{ fontSize: '16px', fontWeight: '600', color: '#2d3436', margin: 0, lineHeight: '1.7' }}>
                                {analysis.prediction2026}
                            </p>
                        </div>
                    </div>
                )}

                {/* Closing Message */}
                <div style={{ background: 'linear-gradient(135deg, #f8f9fa 0%, #e9ecef 100%)', padding: '30px', borderRadius: '16px', textAlign: 'center', marginTop: '40px' }}>
                    <div style={{ fontSize: '18px', fontWeight: '700', color: '#333', marginBottom: '10px' }}>
                        Terima kasih sudah menggunakan RecapChat! 🎉
                    </div>
                    <div style={{ fontSize: '14px', color: '#666', lineHeight: '1.6' }}>
                        Semoga recap ini bisa jadi kenangan indah untuk kalian berdua.
                    </div>
                </div>

                {/* Footer */}
                <div style={{ position: 'absolute', bottom: '40px', left: '60px', right: '60px', textAlign: 'center', color: '#999', fontSize: '10px', borderTop: '1px solid #e9ecef', paddingTop: '15px' }}>
                    <div>Generated by RecapChat.app • {new Date().toLocaleDateString('id-ID')}</div>
                    <div style={{ marginTop: '5px' }}>Halaman {totalPages}/{totalPages}</div>
                </div>
            </div>
        </div>
    );
};
