import React from 'react';
import { ChatData, AnalysisResult } from '../types';
import { Sparkles, MessageCircle, Clock, Heart, TrendingUp, Quote, Users, Zap, Ghost, EyeOff, AlertCircle, Calendar, ArrowRight, BarChart3 } from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

interface PDFFullReportTheme {
    primary: string;
    secondary: string;
    accent: string;
    bg: string;
    text: string;
    textLight: string;
}

const THEMES: Record<string, PDFFullReportTheme> = {
    pastel: { primary: '#B8A9E6', secondary: '#E6D9FF', accent: '#FF1B6B', bg: '#FFFDFB', text: '#6B6B6B', textLight: '#9A9A9A' },
    gradient: { primary: '#667eea', secondary: '#764ba2', accent: '#FF1B6B', bg: '#f8f9fa', text: '#333333', textLight: '#666666' },
    dark: { primary: '#8b5cf6', secondary: '#1e1b4b', accent: '#f472b6', bg: '#0f172a', text: '#f8fafc', textLight: '#94a3b8' },
    minimal: { primary: '#18181b', secondary: '#e4e4e7', accent: '#27272a', bg: '#ffffff', text: '#18181b', textLight: '#71717a' }
};

interface PDFTemplateProps {
    chatData: ChatData;
    analysis: AnalysisResult;
    theme?: string;
}

// A4 dimensions in pixels at 96 DPI
const A4_WIDTH = 794; // 210mm
const A4_HEIGHT = 1123; // 297mm

const Header = ({ title, theme }: { title: string, theme: PDFFullReportTheme }) => (
    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '30px', borderBottom: `2px solid ${theme.primary}`, paddingBottom: '10px' }}>
        <h2 style={{ fontSize: '24px', fontWeight: '900', color: theme.text, textTransform: 'uppercase', letterSpacing: '1px', margin: 0 }}>
            {title}
        </h2>
        <div style={{ fontSize: '12px', color: theme.textLight }}>Recap Chat Full Report</div>
    </div>
);

const Footer = ({ page, total }: { page: number, total: number }) => (
    <div style={{ position: 'absolute', bottom: '30px', left: '50px', right: '50px', display: 'flex', justifyContent: 'space-between', borderTop: '1px solid #e0e0e0', paddingTop: '15px', fontSize: '10px', color: '#999' }}>
        <div>Generated by ichatrecap.vercel.app</div>
        <div>{new Date().toLocaleDateString('id-ID', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
        <div>Page {page} of {total}</div>
    </div>
);

/**
 * PDF Ringkas Template (1-2 pages)
 */
export const PDFRingkasTemplate: React.FC<PDFTemplateProps> = ({ chatData, analysis, theme }) => {
    return (
        <PDFFullReportTemplate chatData={chatData} analysis={analysis} isRingkas={true} theme={theme} />
    );
};

/**
 * PDF Full Report Template (Multi-page)
 */
export const PDFFullReportTemplate: React.FC<PDFTemplateProps & { isRingkas?: boolean }> = ({ chatData, analysis, isRingkas = false, theme = 'pastel' }) => {
    const currentTheme = THEMES[theme as keyof typeof THEMES] || THEMES.pastel;
    const isDark = theme === 'dark';
    const participant1 = chatData.participants[0] || 'User 1';
    const participant2 = chatData.participants[1] || 'User 2';
    const startDate = chatData.dateRange?.start ? new Date(chatData.dateRange.start).toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric' }) : '-';
    const endDate = chatData.dateRange?.end ? new Date(chatData.dateRange.end).toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric' }) : '-';
    const durationDays = chatData.dateRange?.start && chatData.dateRange?.end
        ? Math.ceil((new Date(chatData.dateRange.end).getTime() - new Date(chatData.dateRange.start).getTime()) / (1000 * 60 * 60 * 24))
        : 0;

    const totalPages = isRingkas ? 2 : 7;

    return (
        <div className="pdf-container" style={{ width: `${A4_WIDTH}px`, backgroundColor: currentTheme.bg, color: currentTheme.text, fontFamily: 'Inter, sans-serif' }}>

            {/* === PAGE 1: COVER === */}
            <div className="pdf-page" style={{ width: `${A4_WIDTH}px`, height: `${A4_HEIGHT}px`, padding: '0', position: 'relative', pageBreakAfter: 'always', overflow: 'hidden' }}>
                <div style={{
                    width: '100%', height: '100%',
                    background: isDark ? 'linear-gradient(135deg, #0f172a 0%, #1e1b4b 100%)' : 'linear-gradient(135deg, #fff0f3 0%, #fff 100%)',
                    display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
                    position: 'relative'
                }}>
                    {/* Background Pattern */}
                    <div style={{ position: 'absolute', inset: 0, opacity: 0.03, backgroundImage: `radial-gradient(${currentTheme.text} 1px, transparent 1px)`, backgroundSize: '30px 30px' }} />

                    <div style={{ textAlign: 'center', zIndex: 10, padding: '0 60px' }}>
                        <div style={{ fontSize: '14px', fontWeight: 'bold', letterSpacing: '4px', color: currentTheme.accent, marginBottom: '20px', textTransform: 'uppercase' }}>
                            Official Report
                        </div>
                        <h1 style={{ fontSize: '48px', fontWeight: '900', color: currentTheme.text, lineHeight: '1.2', marginBottom: '20px' }}>
                            {analysis.storyTitle || 'Chat Wrapped'}<br /><span style={{ color: currentTheme.primary, fontSize: '36px' }}>{new Date().getFullYear()} Edition</span>
                        </h1>
                        <div style={{ width: '80px', height: '6px', background: `linear-gradient(to right, ${currentTheme.primary}, ${currentTheme.secondary})`, borderRadius: '3px', margin: '0 auto 40px' }} />

                        <div style={{ fontSize: '28px', fontWeight: '600', color: currentTheme.text, marginBottom: '10px' }}>
                            {participant1} <span style={{ color: currentTheme.textLight, margin: '0 10px' }}>&times;</span> {participant2}
                        </div>
                        <div style={{ fontSize: '16px', color: currentTheme.textLight, marginBottom: '60px' }}>
                            {startDate} — {endDate}
                        </div>

                        {/* Stats Badges */}
                        <div style={{ display: 'flex', justifyContent: 'center', gap: '30px' }}>
                            <div style={{ textAlign: 'center', padding: '15px 30px', background: isDark ? '#1e293b' : 'white', borderRadius: '15px', boxShadow: '0 10px 30px rgba(0,0,0,0.05)' }}>
                                <div style={{ fontSize: '32px', fontWeight: '900', color: currentTheme.text }}>{chatData.totalMessages?.toLocaleString()}</div>
                                <div style={{ fontSize: '12px', fontWeight: 'bold', color: currentTheme.textLight, textTransform: 'uppercase' }}>Total Pesan</div>
                            </div>
                            <div style={{ textAlign: 'center', padding: '15px 30px', background: isDark ? '#1e293b' : 'white', borderRadius: '15px', boxShadow: '0 10px 30px rgba(0,0,0,0.05)' }}>
                                <div style={{ fontSize: '32px', fontWeight: '900', color: currentTheme.text }}>{durationDays}</div>
                                <div style={{ fontSize: '12px', fontWeight: 'bold', color: currentTheme.textLight, textTransform: 'uppercase' }}>Hari Bersama</div>
                            </div>
                        </div>

                        <div style={{ marginTop: '60px', display: 'inline-block', padding: '8px 16px', background: isDark ? '#1e3a8a' : '#e0f2fe', borderRadius: '20px', color: isDark ? '#bfdbfe' : '#0369a1', fontSize: '12px', fontWeight: 'bold' }}>
                            AI Confidence: {analysis.aiConfidence?.toUpperCase() || 'HIGH'}
                        </div>
                    </div>
                </div>
            </div>

            {/* === PAGE 2: EXECUTIVE SUMMARY & STATS === */}
            <div className="pdf-page" style={{ width: `${A4_WIDTH}px`, height: `${A4_HEIGHT}px`, padding: '50px', position: 'relative', pageBreakAfter: 'always', background: currentTheme.bg }}>
                <Header title="Executive Summary" theme={currentTheme} />

                <div style={{ display: 'flex', gap: '30px', marginBottom: '40px' }}>
                    <div style={{ flex: 1 }}>
                        <h3 style={{ fontSize: '18px', fontWeight: 'bold', marginBottom: '15px', color: currentTheme.secondary }}>AI Overview</h3>
                        <p style={{ fontSize: '14px', lineHeight: '1.8', color: currentTheme.text, textAlign: 'justify', background: isDark ? '#1e293b' : '#f9fafb', padding: '20px', borderRadius: '12px', borderLeft: `4px solid ${currentTheme.secondary}` }}>
                            {analysis.summary}
                        </p>
                    </div>
                </div>

                {/* Highlights Grid */}
                <h3 style={{ fontSize: '18px', fontWeight: 'bold', marginBottom: '20px', color: currentTheme.text }}>Key Highlights</h3>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '15px', marginBottom: '40px' }}>
                    {[
                        { label: 'Mood Dominan', val: analysis.emotionalTone || '-', icon: Heart, color: '#fecdd3', text: '#be123c' },
                        { label: 'Topik Utama', val: analysis.topTopics?.[0]?.topic || '-', icon: MessageCircle, color: '#ddd6fe', text: '#5b21b6' },
                        { label: 'Paling Aktif', val: analysis.communicationStyle?.mostExpressive || '-', icon: Users, color: '#bfdbfe', text: '#1e40af' },
                        { label: 'Hari Tersibuk', val: chatData.busiestDay?.date || '-', icon: Calendar, color: '#bbf7d0', text: '#15803d' },
                        { label: 'Jam Puncak', val: (chatData.busiestHour !== undefined ? `${chatData.busiestHour}:00` : '-'), icon: Clock, color: '#fef08a', text: '#854d0e' },
                        { label: 'Pesan Terpanjang', val: `${chatData.participantStats[participant1]?.averageLength > chatData.participantStats[participant2]?.averageLength ? participant1 : participant2}`, icon: BarChart3, color: '#e5e7eb', text: '#374151' },
                    ].map((item, i) => (
                        <div key={i} style={{ background: isDark ? '#334155' : item.color, padding: '15px', borderRadius: '12px', display: 'flex', flexDirection: 'column', alignItems: 'center', textAlign: 'center' }}>
                            <item.icon size={20} style={{ color: isDark ? '#e2e8f0' : item.text, marginBottom: '8px' }} />
                            <div style={{ fontSize: '10px', textTransform: 'uppercase', fontWeight: 'bold', color: isDark ? '#cbd5e1' : item.text, opacity: 0.7, marginBottom: '4px' }}>{item.label}</div>
                            <div style={{ fontSize: '12px', fontWeight: 'bold', lineHeight: '1.3', color: isDark ? '#f8fafc' : item.text, wordBreak: 'break-word', display: '-webkit-box', WebkitLineClamp: 2, WebkitBoxOrient: 'vertical', overflow: 'hidden' }}>{item.val}</div>
                        </div>
                    ))}
                </div>

                {/* Key Stats Table */}
                <h3 style={{ fontSize: '18px', fontWeight: 'bold', marginBottom: '20px', color: currentTheme.text }}>Statistic Details</h3>
                <div style={{ border: `1px solid ${isDark ? '#334155' : '#e5e7eb'}`, borderRadius: '12px', overflow: 'hidden' }}>
                    <div style={{ display: 'grid', gridTemplateColumns: '2fr 1fr 1fr', background: isDark ? '#1e293b' : '#f3f4f6', padding: '12px 20px', fontSize: '12px', fontWeight: 'bold', color: currentTheme.textLight }}>
                        <div>METRIC</div>
                        <div style={{ textAlign: 'center' }}>{participant1}</div>
                        <div style={{ textAlign: 'center' }}>{participant2}</div>
                    </div>
                    {[
                        { label: 'Total Pesan', k: 'messageCount', fmt: (v: number) => v.toLocaleString() },
                        { label: 'Total Kata', k: 'wordCount', fmt: (v: number) => v.toLocaleString() },
                        { label: 'Rata-rata Panjang Pesan', k: 'averageLength', fmt: (v: number) => `${v} kata` },
                        { label: 'Ghosting Count', k: 'ghostingCount', fmt: (v: number) => `${v}x` },
                        { label: 'Emoji Favorit', k: 'topEmojis', fmt: (v: string[]) => v?.[0] || '-' },
                    ].map((row, i) => (
                        <div key={i} style={{ display: 'grid', gridTemplateColumns: '2fr 1fr 1fr', padding: '12px 20px', borderTop: `1px solid ${isDark ? '#334155' : '#e5e7eb'}`, fontSize: '13px', color: currentTheme.text }}>
                            <div style={{ fontWeight: '500' }}>{row.label}</div>
                            <div style={{ textAlign: 'center' }}>{row.fmt(chatData.participantStats[participant1]?.[row.k as keyof typeof chatData.participantStats[string]] as any || 0)}</div>
                            <div style={{ textAlign: 'center' }}>{row.fmt(chatData.participantStats[participant2]?.[row.k as keyof typeof chatData.participantStats[string]] as any || 0)}</div>
                        </div>
                    ))}
                </div>

                <Footer page={2} total={totalPages} />
            </div>

            {/* === PAGE 3: CHARTS (Activity Analysis) === */}
            {!isRingkas && (
                <div className="pdf-page" style={{ width: `${A4_WIDTH}px`, height: `${A4_HEIGHT}px`, padding: '50px', position: 'relative', pageBreakAfter: 'always', background: currentTheme.bg }}>
                    <Header title="Activity Analysis" theme={currentTheme} />

                    {/* Daily Activity Chart */}
                    <div style={{ marginBottom: '40px' }}>
                        <h3 style={{ fontSize: '16px', fontWeight: 'bold', marginBottom: '10px', color: currentTheme.text, display: 'flex', alignItems: 'center', gap: '8px' }}>
                            <BarChart3 size={18} color={currentTheme.accent} /> Grafik Aktivitas Harian
                        </h3>
                        <div style={{ width: '100%', height: '250px', border: `1px solid ${isDark ? '#334155' : '#eee'}`, borderRadius: '12px', padding: '10px' }}>
                            <ResponsiveContainer width="100%" height="100%">
                                <AreaChart data={chatData.dailyDistribution}>
                                    <CartesianGrid strokeDasharray="3 3" vertical={false} stroke={isDark ? '#334155' : '#eee'} />
                                    <XAxis dataKey="date" hide />
                                    <YAxis hide />
                                    <Area type="monotone" dataKey="count" stroke={currentTheme.primary} fill={currentTheme.primary} fillOpacity={0.2} isAnimationActive={false} />
                                </AreaChart>
                            </ResponsiveContainer>
                        </div>
                    </div>

                    {/* Hourly Activity Chart */}
                    <div style={{ marginBottom: '40px' }}>
                        <h3 style={{ fontSize: '16px', fontWeight: 'bold', marginBottom: '10px', color: currentTheme.text, display: 'flex', alignItems: 'center', gap: '8px' }}>
                            <Clock size={18} color={currentTheme.accent} /> Jam Paling Aktif (Heatmap)
                        </h3>
                        <div style={{ width: '100%', height: '250px', border: `1px solid ${isDark ? '#334155' : '#eee'}`, borderRadius: '12px', padding: '10px' }}>
                            <ResponsiveContainer width="100%" height="100%">
                                <BarChart data={chatData.hourlyDistribution}>
                                    <CartesianGrid strokeDasharray="3 3" vertical={false} stroke={isDark ? '#334155' : '#eee'} />
                                    <XAxis dataKey="hour" fontSize={10} tickFormatter={(val) => `${val}:00`} tick={{ fill: currentTheme.textLight }} />
                                    <YAxis fontSize={10} tick={{ fill: currentTheme.textLight }} />
                                    <Bar dataKey="count" fill={currentTheme.secondary} radius={[4, 4, 0, 0]} isAnimationActive={false} />
                                </BarChart>
                            </ResponsiveContainer>
                        </div>
                    </div>

                    {/* Balance Pie Chart */}
                    <div style={{ display: 'flex', gap: '30px', alignItems: 'center', background: isDark ? '#1e293b' : '#f9fafb', padding: '20px', borderRadius: '12px' }}>
                        <div style={{ width: '150px', height: '150px' }}>
                            <ResponsiveContainer width="100%" height="100%">
                                <PieChart>
                                    <Pie
                                        data={[
                                            { name: participant1, value: chatData.participantStats[participant1]?.messageCount || 0 },
                                            { name: participant2, value: chatData.participantStats[participant2]?.messageCount || 0 }
                                        ]}
                                        cx="50%"
                                        cy="50%"
                                        innerRadius={40}
                                        outerRadius={70}
                                        fill="#8884d8"
                                        paddingAngle={5}
                                        dataKey="value"
                                        isAnimationActive={false}
                                    >
                                        <Cell fill={currentTheme.primary} />
                                        <Cell fill={currentTheme.accent} />
                                    </Pie>
                                </PieChart>
                            </ResponsiveContainer>
                        </div>
                        <div style={{ flex: 1 }}>
                            <h3 style={{ fontSize: '16px', fontWeight: 'bold', marginBottom: '10px', color: currentTheme.text }}>Chat Balance</h3>
                            <div style={{ marginBottom: '8px', display: 'flex', alignItems: 'center', gap: '10px' }}>
                                <div style={{ width: '12px', height: '12px', borderRadius: '50%', background: currentTheme.primary }}></div>
                                <div style={{ fontSize: '14px', color: currentTheme.text }}>{participant1}: <strong>{((chatData.participantStats[participant1]?.messageCount || 0) / chatData.totalMessages * 100).toFixed(1)}%</strong></div>
                            </div>
                            <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                                <div style={{ width: '12px', height: '12px', borderRadius: '50%', background: currentTheme.accent }}></div>
                                <div style={{ fontSize: '14px', color: currentTheme.text }}>{participant2}: <strong>{((chatData.participantStats[participant2]?.messageCount || 0) / chatData.totalMessages * 100).toFixed(1)}%</strong></div>
                            </div>
                        </div>
                    </div>

                    <Footer page={3} total={totalPages} />
                </div>
            )}

            {/* === PAGE 4: EMOTIONS & TOPICS === */}
            {!isRingkas && (
                <div className="pdf-page" style={{ width: `${A4_WIDTH}px`, height: `${A4_HEIGHT}px`, padding: '50px', position: 'relative', pageBreakAfter: 'always', background: currentTheme.bg }}>
                    <Header title="Mood & Topics" theme={currentTheme} />

                    {/* Monthly Moods */}
                    <div style={{ marginBottom: '40px' }}>
                        <h3 style={{ fontSize: '16px', fontWeight: 'bold', marginBottom: '15px', color: currentTheme.text }}>Perjalanan Emosi (Bulanan)</h3>
                        <div style={{ display: 'flex', gap: '8px', overflow: 'visible', paddingBottom: '5px' }}>
                            {analysis.monthlyMoods?.slice(0, 12).map((m, i) => ( // Limit to 12 months to fit
                                <div key={i} style={{ flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
                                    <div style={{ width: '100%', height: '100px', background: isDark ? '#334155' : '#f3f4f6', borderRadius: '20px', position: 'relative', overflow: 'hidden' }}>
                                        <div style={{
                                            position: 'absolute', bottom: 0, left: 0, right: 0,
                                            height: `${m.intensity * 10}%`,
                                            background: m.mood.includes('Senang') || m.mood.includes('Hangat') ? '#fca5a5' : '#93c5fd'
                                        }} />
                                    </div>
                                    <div style={{ fontSize: '10px', marginTop: '5px', fontWeight: 'bold', color: currentTheme.textLight }}>{m.month.split(' ')[0]}</div>
                                    <div style={{ fontSize: '8px', color: currentTheme.textLight, textAlign: 'center' }}>{m.mood}</div>
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* Topics Cloud */}
                    <div style={{ marginBottom: '40px' }}>
                        <h3 style={{ fontSize: '16px', fontWeight: 'bold', marginBottom: '15px', color: currentTheme.text }}>Topik Paling Sering Dibahas</h3>
                        <div style={{ display: 'flex', flexWrap: 'wrap', gap: '10px' }}>
                            {analysis.topTopics?.map((msg, i) => (
                                <div key={i} style={{
                                    padding: '8px 12px', borderRadius: '20px',
                                    background: i < 3 ? currentTheme.primary : i < 6 ? '#e0e7ff' : (isDark ? '#334155' : '#f3f4f6'),
                                    color: i < 3 ? '#fff' : (isDark ? '#e2e8f0' : '#4b5563'),
                                    fontSize: i < 3 ? '14px' : '12px',
                                    fontWeight: i < 3 ? 'bold' : 'normal'
                                }}>
                                    {msg.emoji} {msg.topic} <span style={{ opacity: 0.7, fontSize: '0.8em', marginLeft: '4px' }}>{msg.count}</span>
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* Communication Style Cards */}
                    <h3 style={{ fontSize: '16px', fontWeight: 'bold', marginBottom: '15px', color: currentTheme.text }}>Gaya Komunikasi</h3>
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px' }}>
                        <div style={{ background: isDark ? '#431407' : '#fff7ed', padding: '20px', borderRadius: '12px', border: `1px solid ${isDark ? '#7c2d12' : '#ffedd5'}` }}>
                            <div style={{ fontSize: '12px', color: isDark ? '#fb923c' : '#9a3412', fontWeight: 'bold', textTransform: 'uppercase', marginBottom: '5px' }}>Top Emoji</div>
                            <div style={{ fontSize: '24px', marginBottom: '5px', color: currentTheme.text }}>{analysis.topEmoji1} vs {analysis.topEmoji2}</div>
                            <div style={{ fontSize: '12px', color: isDark ? '#fdba74' : '#c2410c' }}>Preferensi emoji kalian menunjukkan {analysis.emojiInsight || 'kecocokan unik!'}</div>
                        </div>
                        <div style={{ background: isDark ? '#064e3b' : '#f0fdf4', padding: '20px', borderRadius: '12px', border: `1px solid ${isDark ? '#065f46' : '#dcfce7'}` }}>
                            <div style={{ fontSize: '12px', color: isDark ? '#4ade80' : '#166534', fontWeight: 'bold', textTransform: 'uppercase', marginBottom: '5px' }}>Reply Speed</div>
                            <div style={{ fontSize: '14px', fontWeight: 'bold', marginBottom: '5px', color: currentTheme.text }}>
                                {analysis.replyBadge1 === 'Si Kilat' ? participant1 : participant2} lebih sat-set!
                            </div>
                            <div style={{ fontSize: '12px', color: isDark ? '#86efac' : '#15803d' }}>
                                Rata-rata balas: {analysis.avgReplyTime1} vs {analysis.avgReplyTime2}
                            </div>
                        </div>
                    </div>

                    <Footer page={4} total={totalPages} />
                </div>
            )}

            {/* === PAGE 5: TIMELINE & MOMENTS === */}
            {!isRingkas && (
                <div className="pdf-page" style={{ width: `${A4_WIDTH}px`, height: `${A4_HEIGHT}px`, padding: '50px', position: 'relative', pageBreakAfter: 'always', background: currentTheme.bg }}>
                    <Header title="Timeline & Moments" theme={currentTheme} />

                    {/* Phases Timeline */}
                    <div style={{ marginBottom: '40px' }}>
                        <h3 style={{ fontSize: '16px', fontWeight: 'bold', marginBottom: '20px', color: currentTheme.text }}>Fase Hubungan</h3>
                        <div style={{ position: 'relative', paddingLeft: '20px', borderLeft: `2px solid ${isDark ? '#334155' : '#e5e7eb'}` }}>
                            {analysis.phases?.map((phase, i) => (
                                <div key={i} style={{ marginBottom: '25px', position: 'relative' }}>
                                    <div style={{ position: 'absolute', left: '-26px', top: '0', width: '14px', height: '14px', borderRadius: '50%', background: phase.mood === 'warm' ? '#fbbf24' : '#9ca3af', border: `2px solid ${currentTheme.bg}` }}></div>
                                    <div style={{ fontSize: '14px', fontWeight: 'bold', color: currentTheme.text }}>{phase.name}</div>
                                    <div style={{ fontSize: '11px', color: currentTheme.textLight, marginBottom: '4px' }}>{phase.period}</div>
                                    <div style={{ fontSize: '12px', color: currentTheme.text, background: isDark ? '#1e293b' : '#f9fafb', padding: '10px', borderRadius: '8px', lineHeight: '1.5' }}>
                                        {phase.description}
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* Special Moments List */}
                    <h3 style={{ fontSize: '16px', fontWeight: 'bold', marginBottom: '15px', color: currentTheme.text }}>Momen Spesial</h3>
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr', gap: '10px' }}>
                        {analysis.keyMoments?.slice(0, 4).map((moment, i) => (
                            <div key={i} style={{ display: 'flex', gap: '15px', alignItems: 'flex-start', background: currentTheme.bg, padding: '10px 0', borderBottom: `1px solid ${isDark ? '#334155' : '#f3f4f6'}` }}>
                                <div style={{ fontSize: '24px' }}>✨</div>
                                <div>
                                    <div style={{ fontSize: '14px', fontWeight: 'bold', color: currentTheme.text }}>{moment.title}</div>
                                    <div style={{ fontSize: '11px', color: currentTheme.textLight, fontStyle: 'italic', marginBottom: '2px' }}>{moment.date}</div>
                                    <div style={{ fontSize: '12px', color: currentTheme.text }}>{moment.description}</div>
                                </div>
                            </div>
                        ))}
                    </div>

                    <Footer page={5} total={totalPages} />
                </div>
            )}

            {/* === PAGE 6: QUOTES & MEMORABLE MESSAGES === */}
            {!isRingkas && (
                <div className="pdf-page" style={{ width: `${A4_WIDTH}px`, height: `${A4_HEIGHT}px`, padding: '50px', position: 'relative', pageBreakAfter: 'always', background: currentTheme.bg }}>
                    <Header title="Hall of Fame" theme={currentTheme} />

                    {/* Best Quote Hero */}
                    <div style={{ background: isDark ? '#1e293b' : 'linear-gradient(135deg, #f3e8ff 0%, #e0e7ff 100%)', padding: '40px', borderRadius: '20px', textAlign: 'center', marginBottom: '50px', position: 'relative' }}>
                        <Quote size={40} color={currentTheme.primary} style={{ opacity: 0.3, position: 'absolute', top: '20px', left: '20px' }} />
                        <div style={{ fontSize: '12px', fontWeight: 'bold', color: currentTheme.primary, textTransform: 'uppercase', marginBottom: '10px' }}>Quote of the Year</div>
                        <div style={{ fontSize: '22px', fontStyle: 'italic', fontWeight: '600', color: currentTheme.text, lineHeight: '1.6', marginBottom: '20px' }}>
                            "{analysis.bestQuote}"
                        </div>
                        <div style={{ fontSize: '14px', fontWeight: 'bold', color: currentTheme.text }}>— {analysis.quoteAuthor}</div>
                        <div style={{ fontSize: '12px', color: currentTheme.textLight, marginTop: '5px' }}>{analysis.quoteDate}</div>
                    </div>

                    {/* Runner Up Quotes */}
                    <h3 style={{ fontSize: '16px', fontWeight: 'bold', marginBottom: '20px', color: currentTheme.text }}>Runner Ups & Iconic Lines</h3>
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px' }}>
                        {analysis.runnerUpQuotes?.map((quote, i) => (
                            <div key={i} style={{ background: isDark ? '#1e293b' : '#f9fafb', padding: '20px', borderRadius: '15px' }}>
                                <div style={{ fontSize: '14px', fontStyle: 'italic', marginBottom: '10px', color: currentTheme.text }}>"{quote.text}"</div>
                                <div style={{ fontSize: '12px', fontWeight: 'bold', color: currentTheme.textLight }}>— {quote.author}</div>
                            </div>
                        ))}
                    </div>

                    {/* Ghosting & Silence (Mini Section) */}
                    <div style={{ marginTop: '50px', background: isDark ? '#450a0a' : '#fef2f2', padding: '25px', borderRadius: '15px', border: `1px solid ${isDark ? '#7f1d1d' : '#fee2e2'}` }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '10px' }}>
                            <Ghost size={20} color="#ef4444" />
                            <h3 style={{ fontSize: '16px', fontWeight: 'bold', color: '#b91c1c', margin: 0 }}>Ghosting Alert</h3>
                        </div>
                        <p style={{ fontSize: '13px', color: isDark ? '#fca5a5' : '#7f1d1d', lineHeight: '1.6' }}>
                            {analysis.ghostingInsight || 'Kalian cukup intens berkomunikasi tanpa jeda lama.'}
                        </p>
                        {chatData.silencePeriods?.[0] && (
                            <div style={{ marginTop: '10px', fontSize: '12px', color: '#991b1b', fontWeight: 'bold' }}>
                                Jeda terlama: {chatData.silencePeriods[0].durationDays} hari (Dipegang oleh {chatData.silencePeriods[0].breaker} yang memecah keheningan)
                            </div>
                        )}
                    </div>

                    <Footer page={6} total={totalPages} />
                </div>
            )}

            {/* === PAGE 7: AI REFLECTION & CLOSING === */}
            {!isRingkas && (
                <div className="pdf-page" style={{ width: `${A4_WIDTH}px`, height: `${A4_HEIGHT}px`, padding: '50px', position: 'relative', background: currentTheme.bg }}>
                    <Header title="AI Reflection" theme={currentTheme} />

                    {/* AI Prediction Box */}
                    <div style={{ background: isDark ? '#172554' : '#f0f9ff', border: `2px solid ${isDark ? '#1e40af' : '#bae6fd'}`, padding: '30px', borderRadius: '20px', marginBottom: '40px' }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '15px' }}>
                            <Sparkles size={24} color={isDark ? '#38bdf8' : '#0284c7'} />
                            <h3 style={{ fontSize: '18px', fontWeight: 'bold', color: isDark ? '#38bdf8' : '#0369a1', margin: 0 }}>Prediksi Hubungan 2026</h3>
                        </div>
                        <p style={{ fontSize: '15px', lineHeight: '1.8', color: isDark ? '#e0f2fe' : '#0c4a6e' }}>
                            {analysis.prediction2026 || analysis.futurePredict}
                        </p>

                        <div style={{ marginTop: '20px', display: 'flex', gap: '10px', flexWrap: 'wrap' }}>
                            {analysis.strengthPoints?.map((s, i) => (
                                <span key={i} style={{ fontSize: '12px', background: isDark ? '#1e3a8a' : '#fff', padding: '5px 10px', borderRadius: '10px', color: isDark ? '#e0f2fe' : '#0284c7', border: `1px solid ${isDark ? '#1e40af' : '#e0f2fe'}` }}>
                                    ✅ {s}
                                </span>
                            ))}
                        </div>
                    </div>

                    {/* Reflection */}
                    <div style={{ marginBottom: '60px' }}>
                        <h3 style={{ fontSize: '18px', fontWeight: 'bold', marginBottom: '15px', color: currentTheme.text }}>Pesan Penutup</h3>
                        <p style={{ fontSize: '16px', fontStyle: 'italic', lineHeight: '1.8', color: currentTheme.textLight, padding: '0 10px' }}>
                            "{analysis.reflection}"
                        </p>
                    </div>

                    {/* Final Branding */}
                    <div style={{ textAlign: 'center', marginTop: 'auto', paddingBottom: '100px' }}>
                        <div style={{ width: '40px', height: '5px', background: currentTheme.accent, margin: '0 auto 20px', borderRadius: '5px' }}></div>
                        <h2 style={{ fontSize: '24px', fontWeight: '900', color: currentTheme.text }}>Recap Chat</h2>
                        <div style={{ fontSize: '14px', color: currentTheme.textLight, marginTop: '5px' }}>Turn your chats into stories.</div>
                    </div>

                    <Footer page={7} total={totalPages} />
                </div>
            )}
        </div>
    );
};
